In procedural programming, the program is divided into small parts called functions.	In object-oriented programming, the program is divided into small                                                                                           parts called objects.
Procedural programming follows a top-down approach                                 .	Object-oriented programming follows a bottom-up approach.
There is no access specifier in procedural programmin                              g.	Object-oriented programming has access specifiers like private                                                                                           , public, protected, etc.
Adding new data and functions is not eas                                             y.	Adding new data and function is easy.
Procedural programming does not have any proper way of hiding data so it is less secure.	Object-oriented programming provides data hiding so it is m                                                                                            ore secure.
In procedural programming, overloading is not poss                                  ible.	Overloading is possible in object-oriented programming.
In procedural programming, there is no concept of data hiding and inherit           ance.	In object-oriented programming, the concept of data hidin                                                                                             g and inheritance is used.
In procedural programming, the function is more important than th                 e data.	In object-oriented programming, data is more importan                                                                                                t than function.
Procedural programming is based on the unreal                                     world.	Object-oriented programming is based on the real world.
Procedural programming is used for designing medium-sized                  programs.	Object-oriented programming is used for designing l                                                                                               arge and complex programs.
Procedural programming uses the concept of procedure abs                   traction.	Object-oriented programming uses the concept of data abstraction.
Code reusability absent in procedural pr                                         ogramming,	Code reusability present in object-oriented programming.
Examples: C, FORTRAN, Pascal,                                                        Basic, etc.	Examples: C++, Java, Python, C#, etc.

In [1]:
print("hello")

hello


In [1]:
type(2)

int

In [2]:
type(2.5)

float

In [3]:
x=3

In [4]:
y="hello"
print(y)

hello


In [6]:
name=None
type(name)

NoneType

In [9]:
x=False
type(x)

bool

In [8]:
'''"my name is "yuvraj""'''

'"my name is "yuvraj""'

In [13]:
li=[1,2,3,'yuv',5]
print(li[0])
type(li)

1


list

In [25]:
dfy=[1,2,3,4,5,56,6,"u",'f','d']
dfy.append('p')
dfy.extend(['p','q'])
dfy.insert(2,3)
dfy.remove(3) #removes value by the value 
dfy.pop(2)#removes and return the value by index
gt=[1,2,3,4,5]
del(gt[4])#delete without returning value by index
print(gt)
print(dfy)
del(dfy[1::2])#delete alternately 
#gt.clear()#remvoes all elments at a go
print(dfy)

          

[1, 2, 3, 4]
[1, 2, 4, 5, 56, 6, 'u', 'f', 'd', 'p', 'p', 'q']


[1, 4, 56, 'u', 'd', 'p']

In [28]:
#create a program to mangae the students marks and attendance for a college.
piet2sem=["ayush",[1,gt,3]]
piet2sem[1][1]

[1, 2, 3, 4]

In [32]:
v=[]
for i in range(4):
    v.append([input("enter the name"),int(input("enter the marks")),int(input("enter the attendance"))])
print(v)

enter the name A
enter the marks 34
enter the attendance 45
enter the name C
enter the marks 45
enter the attendance 67
enter the name V
enter the marks 56
enter the attendance 78
enter the name B
enter the marks 78
enter the attendance 89


[['A', 34, 45], ['C', 45, 67], ['V', 56, 78], ['B', 78, 89]]

In [3]:
list12=[1,2,3,4,5,6,7]
list12.reverse()
print(list12)
list12.sort()
list12


[7, 6, 5, 4, 3, 2, 1]


[1, 2, 3, 4, 5, 6, 7]

In [10]:
#string datatype 
x='Hello@2123'
bk=x.upper()#temporary view not change original string
print(bk,x)
bk+x#concatenation of string


#list,string,tuples are sequential



HELLO@2123 Hello@2123


In [43]:
#in sets cannot be indexed no fixed index
reg={1,2,3,4,5}  #set declaration
reg.add(6)
reg.remove(6)
reg.update({'a','b',"hello"})#change the original set
npk=reg.union({6,7})#does not change the original sets
print(npk)
reg.remove(3)
print(reg)
reg.pop()#pop takes no argument and return the removed value from starting 
reg
x=set()#empty set
type(x)
z=set([1,2,3])
print(z)


{1, 2, 3, 4, 5, 'hello', 6, 7, 'b', 'a'}
{1, 2, 4, 5, 'hello', 'b', 'a'}
{1, 2, 3}


set

In [49]:
#dictionary=>key value pairs
stu={
    'one':2,
    'two':4,
    (12,13):5,
'maths':[1,2,3,4]
}
print(stu)
print(stu['one'])#using key accessing value
#key should be unique but value can be duplicate
#if duplicate key is used then the recent key value pair will replace the old value
#tuple can be used as key because it is immutable.only immutable datatype can be used as keys
#search time is constant faster than list but sorting is not efficient
stu['science']=[1,2,3,4]#add new key value pair in dictionary
print(stu)
stu['science']=[2,6,8,9]#we can change values also of associated key
print(stu)
ml flow apache spark



{'one': 2, 'two': 4, (12, 13): 5, 'maths': [1, 2, 3, 4]}
2
{'one': 2, 'two': 4, (12, 13): 5, 'maths': [1, 2, 3, 4], 'science': [1, 2, 3, 4]}
{'one': 2, 'two': 4, (12, 13): 5, 'maths': [1, 2, 3, 4], 'science': [2, 6, 8, 9]}


In [2]:
import mysql.connector

# Replace these values with your actual database information
host = "20.204.3.99"  # Database host
user = "YTHOR"  # Database username
password = "Yuvraj9983318185"  # Database password
database = "user1"  # Database name

try:
    # Create a connection to the database
    connection = mysql.connector.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )

    if connection.is_connected():
        print("Connected to the database")

        # Perform database operations here

except mysql.connector.Error as e:
    print("Error connecting to the database:", e)

finally:
    # Close the connection when done
    if 'connection' in locals():
        connection.close()
        print("Connection closed")


Error connecting to the database: 2003 (HY000): Can't connect to MySQL server on '20.204.3.99:3306' (10060)


In [4]:
import numpy as np

In [5]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

In [10]:
a=np.array([[1,2,3,4],[2,3,4,5]])
print(a)#there is no commas in the output this makes it different from list
a.shape

[[1 2 3 4]
 [2 3 4 5]]


(2, 4)

In [11]:
a.ndim#GIVES THE DIMENSION OF THE ARRAY

2

In [13]:
b=np.array([[[4]]])
b.shape
print(b)


[[[4]]]


In [40]:
#create an array of (5,4) and (3,1,2)  and (3,0,2)shape
c=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8],[5,6,7,8],[4,5,7,8]])
print(c.shape)
arr3 = np.array([
    [[11, 12]],

    
    [[15, 16]],

    [[3,4]]

])
print(arr3.shape)
ar6=np.array([[[2,3]],[[3,5]],[[5,8]]])
print(ar6.shape)



(5, 4)
(3, 1, 2)
(3, 1, 1)


In [ ]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import numpy as np

# Replace with your own JSON key file path and spreadsheet URL
json_keyfile = 'path_to_your_json_key_file.json'
spreadsheet_url = 'your_spreadsheet_url_here'

# Authenticate using the JSON key file
scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_name(json_keyfile, scope)
client = gspread.authorize(credentials)

# Open the specified spreadsheet
spreadsheet = client.open_by_url(spreadsheet_url)
worksheet = spreadsheet.get_worksheet(0)  # You can specify the worksheet index

# Get all values from the worksheet
values = worksheet.get_all_values()

# Convert the values to a NumPy array
numpy_array = np.array(values)

print(numpy_array)


In [73]:
import numpy as np
z=np.zeros((3,4),dtype=np.int8)
print(z)

k=np.ones((2,3),dtype=float)
print(k)

j=np.arange(10,100)
print(j)

t=np.linspace(1,2,num=5,endpoint=False)#whether to include the last value or not 
print(t)
t[0]=67#only value mutable not size mutable
print(t)


pkm=np.array([np.arange(1,5),np.arange(10,14)])
print(pkm)
print(pkm[0])#print first row
print(pkm[0,0])#print first element of first row
print(pkm[0:2,1:3])#array slicing for 2d array
jkt=np.array([np.arange(1,37)])
print(jkt)

h=jkt.reshape(3,4,3)
print(h)
print(h[0::2,1::2,1::2])

ko=np.zeros((4,4,7,2),dtype=np.int8)
print(ko)
kp=import numpy as np



[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
[1.  1.2 1.4 1.6 1.8]
[67.   1.2  1.4  1.6  1.8]
[[ 1  2  3  4]
 [10 11 12 13]]
[1 2 3 4]
1
[[ 2  3]
 [11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32 33 34 35 36]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[[[ 5]
  [11]]

 [[29]
  [35]]]
[[[[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0

In [2]:
import numpy as np
a=np.array([np.arange(1,6),np.arange(11,16)])
t=[1,2,3]#print 2nd 3rd and 4th element
print(a[0,t])#fancy indexing 

[2 3 4]


In [ ]:
#to use conditions and get a numpy array as result

In [6]:
c=np.array([1,9,6,4,2,7,6,5])
b=c>4
print(b)
k=c[b]#filtering elements greater than 4
print(k)

[False  True  True False False  True  True  True]
[9 6 7 6 5]


In [9]:
c=np.array([1,9,6,4,2,7,6,5])
arr7=c.reshape((2,4))
c[0]=67
print(arr7)
#so conclusion is c and arr7 is pointing to same array if we change any one the change in other also can be seen so both point  to soame location
#slicing and reshaping points to the same memory location and make chagnes in same array it creates view to save memory and time to make fast operations  
arr7=c.reshape((2,4)).copy()# this will allocate different memory location

[[67  9  6  4]
 [ 2  7  6  5]]


In [25]:
ar8=np.array([[67,9  ,6  ,4],
 [ 2 , 7  ,6  ,5]])
total=np.sum(ar8)#sums all the values of array
print(total)
#axis=0 then vertical 
#axis=1 then horizontal
print(np.sum(ar8,axis=0))
print(np.mean(ar8,dtype=int))
print(np.mean(ar8,dtype=int,axis=1))

pi=round(3.123,ndigits=1)#using round function
print(pi)


arrt8=np.array([[67,9  ,6  ,4],
 [ 2 , 7  ,6  ,5]])
print(np.mean(arrt8,where=[[True],[False]]))#only first block mean will be taken


106
[69 16 12  9]
13
[21  5]
3.1
21.5


In [49]:
#numpy project and operations
import numpy as np
temper= np.array([[
        
            [[9, 20], [13, 31], [8, 21], [13, 25], [9, 29], [15, 20], [10, 25]],
            [[13, 23], [9, 23], [13, 21], [-13, 32], [15, 25], [13, 31], [15, 29]],
            [[9, 24], [6, 26], [7, 30], [10, 30], [7, 30], [12, 22], [11, 32]],
            [[13, 30], [12, 26], [15, 26], [15, 29], [8, 25], [11, 27], [15, 24]]
        
    ],
    
    [
        
            [[6, 20], [13, 32], [13, 28], [15, 25], [10, 31], [12, 23], [13, 30]],
            [[9, 32], [6, 32], [8, 30], [7, 32], [7, 32], [14, 29], [9, 21]],
            [[14, 23], [11, 23], [14, 29], [15, 23], [15, 30], [10, 31], [13, 30]],
            [[13, 24], [10, 29], [12, 24], [6, 31], [13, 31], [13, 29], [7, 25]]
        
    ],
    [
        
            [[8, 18], [4, 19], [6, 18], [2, 22], [2, 18], [2, 5], [21, 5]],
            [[7, 20], [3, 21], [3, 20], [5, 20], [3, 18], [2, 6], [20, 6]],
            [[4, 19], [5, 21], [5, 18], [5, 21], [3, 19], [7, 6], [22, 4]],
            [[8, 22], [2, 20], [2, 22], [4, 20], [7, 22], [7, 2], [22, 5]]
        
    ],
    [
        
            [[7, 22], [10, 19], [-10, 18], [11, 20], [8, 20], [9, 71], [22, 10]],
            [[8, 22], [9, 21], [10, 22], [8, 19], [9, 18], [11, 11], [18, 11]],
            [[8, 21], [11, 20], [8, 22], [10, 18], [7, 18], [7, 7], [19, 7]],
            [[7, 19], [9, 22], [8, 22], [11, 18], [12, 22], [8, 11], [21, 8]]
        
    ]])
print("the shape of the array is ", temper.shape,"\n and dimension is ",temper.ndim)#2
#3print the temperatures of first week of every month
print("the temperatures of first week of every month",temper[:,0])
#4. Print the temperatures for Tuesday of each month.
print("the temperatures for Tuesday of each month is ",temper[:,:,1])
#5. Print only the maximum temperature for all the weekdays of Dec and Feb.
print("the maximum temperature for all the weekdays of Dec and Feb",temper[1::2,:,:,0])
#6 Print all the days along with the week number in November when the minimum temperature was less than 8 degrees.
print("ans:6")
b=temper[0,:,:,0]
d=b<8
weeks=np.where(d)
dict1={0:"monday",
       1:"tuesday",
       2:"wednesday",
       3:"thrusday",
       4:"friday",
       5:"saturday",
       6:"sunday"}
for i in range(len(weeks[0])):
    print("week =",weeks[0][i]+1,", day =",dict1[weeks[1][i]])




#7. Print all the weeks in Dec and Jan where the maximum temperature has crossed a threshold of 20 degrees.

kt=temper[1:3,:,:,1]
print(kt)
gfg=np.where(temper[1:3,:,:,1]>20)
monthsdict={0:"december",
            1:"january"}
for i in range(len(gfg[0])):
    print("month=",monthsdict[gfg[0][i]],"week",gfg[1][i]+1,"day",dict1[gfg[2][i]])


#12. Find the average max temperature for the winter months in Jaipur.
print(temper[1,:,:,1].mean(),"is the mean for december")
print(temper[2,:,:,1].mean()," is the mean for january")
#13. Find the weekly min avg temp for the month of Dec in Jaipur
print(temper[1,:,:,0].mean(),"is the mean for min temp in december")
#14. Find the overall avg temp for the months Dec and Jan
print(temper[1,:,:,:].mean(),"is the overall avg temp for the month of december")
print(temper[2,:,:,:].mean(),"is the overall avg temp for the month of january")
#15. Find the least temp experienced by the city in the month of Dec and Jan.
# Also print the exact date( Day/Week/Month) for the same.
print(temper[1,:,:,0:2].min(),"the least temp experienced by the city in the month of Dec")
print(temper[2,:,:,0:2].min(),"the least temp experienced by the city in the month of Jan")
#16. Find the max temp in the month of Feb and return its date(Day/Week/Month)
print(temper[3,:,:,0:2].max(),"the max temp experienced by the city in the month of feb")
#17. Find the days in the month of Nov where the max temp of the day dropped below the avg temp of the month.












the shape of the array is  (4, 4, 7, 2) 
 and dimension is  4
the temperatures of first week of every month [[[  9  20]
  [ 13  31]
  [  8  21]
  [ 13  25]
  [  9  29]
  [ 15  20]
  [ 10  25]]

 [[  6  20]
  [ 13  32]
  [ 13  28]
  [ 15  25]
  [ 10  31]
  [ 12  23]
  [ 13  30]]

 [[  8  18]
  [  4  19]
  [  6  18]
  [  2  22]
  [  2  18]
  [  2   5]
  [ 21   5]]

 [[  7  22]
  [ 10  19]
  [-10  18]
  [ 11  20]
  [  8  20]
  [  9  71]
  [ 22  10]]]
the temperatures for Tuesday of each month is  [[[13 31]
  [ 9 23]
  [ 6 26]
  [12 26]]

 [[13 32]
  [ 6 32]
  [11 23]
  [10 29]]

 [[ 4 19]
  [ 3 21]
  [ 5 21]
  [ 2 20]]

 [[10 19]
  [ 9 21]
  [11 20]
  [ 9 22]]]
the maximum temperature for all the weekdays of Dec and Feb [[[  6  13  13  15  10  12  13]
  [  9   6   8   7   7  14   9]
  [ 14  11  14  15  15  10  13]
  [ 13  10  12   6  13  13   7]]

 [[  7  10 -10  11   8   9  22]
  [  8   9  10   8   9  11  18]
  [  8  11   8  10   7   7  19]
  [  7   9   8  11  12   8  21]]]
ans:6
week = 

In [3]:
import numpy as np
a=np.arange(1,37).reshape(4,9)
print(a)
c=a.flatten(order='k')#convert to 1 d array and makes a copy so slow process so another method
d=a.ravel(order='f')#make a view does not make a different a copy
print(c)
print(d)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
[ 1 10 19 28  2 11 20 29  3 12 21 30  4 13 22 31  5 14 23 32  6 15 24 33
  7 16 25 34  8 17 26 35  9 18 27 36]


In [11]:
#joining numpy arrays
import numpy as np
a=np.arange(1,6)
b=np.arange(11,16)
print(a)
print(b)
print((a+b).sum())
c=np.concatenate((a,b))#default axis 0 vertical
#necessary to have same shape #dimension preserve 
#in 1d only axis 0 is possible not axis 1
d=np.stack((a,b))#not preserve dimension 
e=np.vstack((a,b))
f=np.hstack((a,b))
print(d)
print(e)
print(f)
print(c)

[1 2 3 4 5]
[11 12 13 14 15]
80
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[ 1  2  3  4  5 11 12 13 14 15]
[ 1  2  3  4  5 11 12 13 14 15]


In [12]:
#splitting the array 
import numpy as np
a=np.arange(1,28)
s=np.split(a,9)#split in the factors only
print(s)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]), array([13, 14, 15]), array([16, 17, 18]), array([19, 20, 21]), array([22, 23, 24]), array([25, 26, 27])]


In [1]:
import pandas as pd
pd.__version__

'1.5.2'

In [17]:
a=pd.Series([4,5,3,4])#value mutable and size mutable
print(a)
#lets indexing ''it by alphabets
k=['a','b','c','d']
a=pd.Series([4,5,6,7],k)
print(a)
online=[1,0,1,0]
offline=[4,5,6,7]
marks=pd.DataFrame([online,offline],index=['online','offline'],columns=['A','B','C','D'])
print(marks)

0    4
1    5
2    3
3    4
dtype: int64
a    4
b    5
c    6
d    7
dtype: int64
         A  B  C  D
online   1  0  1  0
offline  4  5  6  7


In [25]:
import pandas as pd 
a=pd.read_csv("C:\\Users\\Yuvraj Singh Rathore\\Desktop\\DIM_MATCH.xlsx - Sheet1.csv")
print(a.head(10))#return first 10 rows 
print(a.tail())#return last rows default is 5 
print(a.info())#gives information about metadata
print(a.describe())

   Match_SK  match_id                        Team1  \
0       546    980964  Royal Challengers Bangalore   
1       547    980966                Gujarat Lions   
2       548    980968        Kolkata Knight Riders   
3       549    980970             Delhi Daredevils   
4       550    980972          Sunrisers Hyderabad   
5       551    980974  Royal Challengers Bangalore   
6       552    980976              Kings XI Punjab   
7       553    980978               Mumbai Indians   
8       554    980980        Kolkata Knight Riders   
9       555    980982              Kings XI Punjab   

                         Team2 match_date  Season_Year  \
0        Kolkata Knight Riders   5/2/2016         2016   
1             Delhi Daredevils   5/3/2016         2016   
2              Kings XI Punjab   5/4/2016         2016   
3      Rising Pune Supergiants   5/5/2016         2016   
4                Gujarat Lions   5/6/2016         2016   
5      Rising Pune Supergiants   5/7/2016         2016   

In [27]:
import pandas as pd
b=pd.read_excel("C:\\Users\\Yuvraj Singh Rathore\\Desktop\\data\\DIM_MATCH.xlsx")#includes the last element of the range passed in it, unlike iloc()

In [16]:
import pandas as pd 
housedata=pd.read_csv("C:\\Users\\Yuvraj Singh Rathore\\Desktop\data\\latest.csv")
print(housedata.info())#shows all necessary information 
print(housedata.shape)#return tuple (rows,column)
print(housedata.index)#return rows
print(housedata.columns)#return column names
print(housedata.count())#return no of entries in column
print(housedata.sum())#gives sum of every indivvidual column
print(housedata.cumsum())#gives cumlated sum of column
#print(housedata.mean())#gives mean
print(housedata.min())
print(housedata.max())
print(housedata.describe().T)# T gives the transpose and describe gives the information about the mean max min
#describe does not work on strings  by default give description of numerical data only in that data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1989 non-null   object 
 1   Open       1989 non-null   float64
 2   High       1989 non-null   float64
 3   Low        1989 non-null   float64
 4   Close      1989 non-null   float64
 5   Volume     1989 non-null   int64  
 6   Adj Close  1989 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 108.9+ KB
None
(1989, 7)
RangeIndex(start=0, stop=1989, step=1)
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close'], dtype='object')
Date         1989
Open         1989
High         1989
Low          1989
Close        1989
Volume       1989
Adj Close    1989
dtype: int64
Date         2016-07-012016-06-302016-06-292016-06-282016-0...
Open                                           26770181.820295
High                                           26933652.010742
L

In [16]:
import pandas as pd 
housedata=pd.read_csv("C:\\Users\\Yuvraj Singh Rathore\\Desktop\data\\latest.csv")
print(housedata.info())#shows all necessary information 
print(housedata.shape)#return tuple (rows,column)
print(housedata.index)#return rows
print(housedata.columns)#return column names
print(housedata.count())#return no of entries in column
print(housedata.sum())#gives sum of every indivvidual column
print(housedata.cumsum())#gives cumlated sum of column
#print(housedata.mean())#gives mean
print(housedata.min())
print(housedata.max())
print(housedata.describe().T)# T gives the transpose and describe gives the information about the mean max min
#describe does not work on strings  by default give description of numerical data only in that data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1989 non-null   object 
 1   Open       1989 non-null   float64
 2   High       1989 non-null   float64
 3   Low        1989 non-null   float64
 4   Close      1989 non-null   float64
 5   Volume     1989 non-null   int64  
 6   Adj Close  1989 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 108.9+ KB
None
(1989, 7)
RangeIndex(start=0, stop=1989, step=1)
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close'], dtype='object')
Date         1989
Open         1989
High         1989
Low          1989
Close        1989
Volume       1989
Adj Close    1989
dtype: int64
Date         2016-07-012016-06-302016-06-292016-06-282016-0...
Open                                           26770181.820295
High                                           26933652.010742
L

In [16]:
import pandas as pd 
housedata=pd.read_csv("C:\\Users\\Yuvraj Singh Rathore\\Desktop\data\\latest.csv")
print(housedata.info())#shows all necessary information 
print(housedata.shape)#return tuple (rows,column)
print(housedata.index)#return rows
print(housedata.columns)#return column names
print(housedata.count())#return no of entries in column
print(housedata.sum())#gives sum of every indivvidual column
print(housedata.cumsum())#gives cumlated sum of column
#print(housedata.mean())#gives mean
print(housedata.min())
print(housedata.max())
print(housedata.describe().T)# T gives the transpose and describe gives the information about the mean max min
#describe does not work on strings  by default give description of numerical data only in that data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1989 non-null   object 
 1   Open       1989 non-null   float64
 2   High       1989 non-null   float64
 3   Low        1989 non-null   float64
 4   Close      1989 non-null   float64
 5   Volume     1989 non-null   int64  
 6   Adj Close  1989 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 108.9+ KB
None
(1989, 7)
RangeIndex(start=0, stop=1989, step=1)
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close'], dtype='object')
Date         1989
Open         1989
High         1989
Low          1989
Close        1989
Volume       1989
Adj Close    1989
dtype: int64
Date         2016-07-012016-06-302016-06-292016-06-282016-0...
Open                                           26770181.820295
High                                           26933652.010742
L

In [16]:
import pandas as pd 
housedata=pd.read_csv("C:\\Users\\Yuvraj Singh Rathore\\Desktop\data\\latest.csv")
print(housedata.info())#shows all necessary information 
print(housedata.shape)#return tuple (rows,column)
print(housedata.index)#return rows
print(housedata.columns)#return column names
print(housedata.count())#return no of entries in column
print(housedata.sum())#gives sum of every indivvidual column
print(housedata.cumsum())#gives cumlated sum of column
#print(housedata.mean())#gives mean
print(housedata.min())
print(housedata.max())
print(housedata.describe().T)# T gives the transpose and describe gives the information about the mean max min
#describe does not work on strings  by default give description of numerical data only in that data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1989 non-null   object 
 1   Open       1989 non-null   float64
 2   High       1989 non-null   float64
 3   Low        1989 non-null   float64
 4   Close      1989 non-null   float64
 5   Volume     1989 non-null   int64  
 6   Adj Close  1989 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 108.9+ KB
None
(1989, 7)
RangeIndex(start=0, stop=1989, step=1)
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close'], dtype='object')
Date         1989
Open         1989
High         1989
Low          1989
Close        1989
Volume       1989
Adj Close    1989
dtype: int64
Date         2016-07-012016-06-302016-06-292016-06-282016-0...
Open                                           26770181.820295
High                                           26933652.010742
L

In [16]:
import pandas as pd 
housedata=pd.read_csv("C:\\Users\\Yuvraj Singh Rathore\\Desktop\data\\latest.csv")
print(housedata.info())#shows all necessary information 
print(housedata.shape)#return tuple (rows,column)
print(housedata.index)#return rows
print(housedata.columns)#return column names
print(housedata.count())#return no of entries in column
print(housedata.sum())#gives sum of every indivvidual column
print(housedata.cumsum())#gives cumlated sum of column
#print(housedata.mean())#gives mean
print(housedata.min())
print(housedata.max())
print(housedata.describe().T)# T gives the transpose and describe gives the information about the mean max min
#describe does not work on strings  by default give description of numerical data only in that data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1989 non-null   object 
 1   Open       1989 non-null   float64
 2   High       1989 non-null   float64
 3   Low        1989 non-null   float64
 4   Close      1989 non-null   float64
 5   Volume     1989 non-null   int64  
 6   Adj Close  1989 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 108.9+ KB
None
(1989, 7)
RangeIndex(start=0, stop=1989, step=1)
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close'], dtype='object')
Date         1989
Open         1989
High         1989
Low          1989
Close        1989
Volume       1989
Adj Close    1989
dtype: int64
Date         2016-07-012016-06-302016-06-292016-06-282016-0...
Open                                           26770181.820295
High                                           26933652.010742
L

In [16]:
import pandas as pd 
housedata=pd.read_csv("C:\\Users\\Yuvraj Singh Rathore\\Desktop\data\\latest.csv")
print(housedata.info())#shows all necessary information 
print(housedata.shape)#return tuple (rows,column)
print(housedata.index)#return rows
print(housedata.columns)#return column names
print(housedata.count())#return no of entries in column
print(housedata.sum())#gives sum of every indivvidual column
print(housedata.cumsum())#gives cumlated sum of column
#print(housedata.mean())#gives mean
print(housedata.min())
print(housedata.max())
print(housedata.describe().T)# T gives the transpose and describe gives the information about the mean max min
#describe does not work on strings  by default give description of numerical data only in that data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1989 non-null   object 
 1   Open       1989 non-null   float64
 2   High       1989 non-null   float64
 3   Low        1989 non-null   float64
 4   Close      1989 non-null   float64
 5   Volume     1989 non-null   int64  
 6   Adj Close  1989 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 108.9+ KB
None
(1989, 7)
RangeIndex(start=0, stop=1989, step=1)
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close'], dtype='object')
Date         1989
Open         1989
High         1989
Low          1989
Close        1989
Volume       1989
Adj Close    1989
dtype: int64
Date         2016-07-012016-06-302016-06-292016-06-282016-0...
Open                                           26770181.820295
High                                           26933652.010742
L

In [16]:
import pandas as pd 
housedata=pd.read_csv("C:\\Users\\Yuvraj Singh Rathore\\Desktop\data\\latest.csv")
print(housedata.info())#shows all necessary information 
print(housedata.shape)#return tuple (rows,column)
print(housedata.index)#return rows
print(housedata.columns)#return column names
print(housedata.count())#return no of entries in column
print(housedata.sum())#gives sum of every indivvidual column
print(housedata.cumsum())#gives cumlated sum of column
#print(housedata.mean())#gives mean
print(housedata.min())
print(housedata.max())
print(housedata.describe().T)# T gives the transpose and describe gives the information about the mean max min
#describe does not work on strings  by default give description of numerical data only in that data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1989 entries, 0 to 1988
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1989 non-null   object 
 1   Open       1989 non-null   float64
 2   High       1989 non-null   float64
 3   Low        1989 non-null   float64
 4   Close      1989 non-null   float64
 5   Volume     1989 non-null   int64  
 6   Adj Close  1989 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 108.9+ KB
None
(1989, 7)
RangeIndex(start=0, stop=1989, step=1)
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close'], dtype='object')
Date         1989
Open         1989
High         1989
Low          1989
Close        1989
Volume       1989
Adj Close    1989
dtype: int64
Date         2016-07-012016-06-302016-06-292016-06-282016-0...
Open                                           26770181.820295
High                                           26933652.010742
L

In [22]:
import pandas as pd 
housedata=pd.read_csv("C:\\Users\\Yuvraj Singh Rathore\\Desktop\data\\latest.csv")
print(housedata.describe(include=[int],percentiles=[0.2,0.7,0.9]).T)

print(housedata.isnull().sum().sum())#return null values
print(housedata["High"])#PRINT THE COLUMNS THAT IS PASSSEDD

print(housedata[housedata.index.isin(range(1,10))])

         count          mean           std        min         20%  \
Volume  1989.0  1.628110e+08  9.392343e+07  8410000.0  92938000.0   

                50%          70%          90%          max  
Volume  135170000.0  178072000.0  282294000.0  674920000.0  
0
0       18002.380859
1       17930.609375
2       17704.509766
3       17409.720703
4       17355.210938
            ...     
1984    11718.280273
1985    11633.780273
1986    11782.349609
1987    11867.110352
1988    11759.959961
Name: High, Length: 1989, dtype: float64
         Date          Open          High           Low         Close  \
1  2016-06-30  17712.759766  17930.609375  17711.800781  17929.990234   
2  2016-06-29  17456.019531  17704.509766  17456.019531  17694.679688   
3  2016-06-28  17190.509766  17409.720703  17190.509766  17409.720703   
4  2016-06-27  17355.210938  17355.210938  17063.080078  17140.240234   
5  2016-06-24  17946.630859  17946.630859  17356.339844  17400.750000   
6  2016-06-23  17844.109375