In procedural programming, the program is divided into small parts called functions.	In object-oriented programming, the program is divided into small                                                                                           parts called objects.
Procedural programming follows a top-down approach                                 .	Object-oriented programming follows a bottom-up approach.
There is no access specifier in procedural programmin                              g.	Object-oriented programming has access specifiers like private                                                                                           , public, protected, etc.
Adding new data and functions is not eas                                             y.	Adding new data and function is easy.
Procedural programming does not have any proper way of hiding data so it is less secure.	Object-oriented programming provides data hiding so it is m                                                                                            ore secure.
In procedural programming, overloading is not poss                                  ible.	Overloading is possible in object-oriented programming.
In procedural programming, there is no concept of data hiding and inherit           ance.	In object-oriented programming, the concept of data hidin                                                                                             g and inheritance is used.
In procedural programming, the function is more important than th                 e data.	In object-oriented programming, data is more importan                                                                                                t than function.
Procedural programming is based on the unreal                                     world.	Object-oriented programming is based on the real world.
Procedural programming is used for designing medium-sized                  programs.	Object-oriented programming is used for designing l                                                                                               arge and complex programs.
Procedural programming uses the concept of procedure abs                   traction.	Object-oriented programming uses the concept of data abstraction.
Code reusability absent in procedural pr                                         ogramming,	Code reusability present in object-oriented programming.
Examples: C, FORTRAN, Pascal,                                                        Basic, etc.	Examples: C++, Java, Python, C#, etc.

In [1]:
print("hello")

hello


In [1]:
type(2)

int

In [2]:
type(2.5)

float

In [3]:
x=3

In [4]:
y="hello"
print(y)

hello


In [6]:
name=None
type(name)

NoneType

In [9]:
x=False
type(x)

bool

In [8]:
'''"my name is "yuvraj""'''

'"my name is "yuvraj""'

In [13]:
li=[1,2,3,'yuv',5]
print(li[0])
type(li)

1


list

In [25]:
dfy=[1,2,3,4,5,56,6,"u",'f','d']
dfy.append('p')
dfy.extend(['p','q'])
dfy.insert(2,3)
dfy.remove(3) #removes value by the value 
dfy.pop(2)#removes and return the value by index
gt=[1,2,3,4,5]
del(gt[4])#delete without returning value by index
print(gt)
print(dfy)
del(dfy[1::2])#delete alternately 
#gt.clear()#remvoes all elments at a go
print(dfy)

          

[1, 2, 3, 4]
[1, 2, 4, 5, 56, 6, 'u', 'f', 'd', 'p', 'p', 'q']


[1, 4, 56, 'u', 'd', 'p']

In [28]:
#create a program to mangae the students marks and attendance for a college.
piet2sem=["ayush",[1,gt,3]]
piet2sem[1][1]

[1, 2, 3, 4]

In [32]:
v=[]
for i in range(4):
    v.append([input("enter the name"),int(input("enter the marks")),int(input("enter the attendance"))])
print(v)

enter the name A
enter the marks 34
enter the attendance 45
enter the name C
enter the marks 45
enter the attendance 67
enter the name V
enter the marks 56
enter the attendance 78
enter the name B
enter the marks 78
enter the attendance 89


[['A', 34, 45], ['C', 45, 67], ['V', 56, 78], ['B', 78, 89]]

In [3]:
list12=[1,2,3,4,5,6,7]
list12.reverse()
print(list12)
list12.sort()
list12


[7, 6, 5, 4, 3, 2, 1]


[1, 2, 3, 4, 5, 6, 7]

In [10]:
#string datatype 
x='Hello@2123'
bk=x.upper()#temporary view not change original string
print(bk,x)
bk+x#concatenation of string


#list,string,tuples are sequential



HELLO@2123 Hello@2123


In [43]:
#in sets cannot be indexed no fixed index
reg={1,2,3,4,5}  #set declaration
reg.add(6)
reg.remove(6)
reg.update({'a','b',"hello"})#change the original set
npk=reg.union({6,7})#does not change the original sets
print(npk)
reg.remove(3)
print(reg)
reg.pop()#pop takes no argument and return the removed value from starting 
reg
x=set()#empty set
type(x)
z=set([1,2,3])
print(z)


{1, 2, 3, 4, 5, 'hello', 6, 7, 'b', 'a'}
{1, 2, 4, 5, 'hello', 'b', 'a'}
{1, 2, 3}


set

In [49]:
#dictionary=>key value pairs
stu={
    'one':2,
    'two':4,
    (12,13):5,
'maths':[1,2,3,4]
}
print(stu)
print(stu['one'])#using key accessing value
#key should be unique but value can be duplicate
#if duplicate key is used then the recent key value pair will replace the old value
#tuple can be used as key because it is immutable.only immutable datatype can be used as keys
#search time is constant faster than list but sorting is not efficient
stu['science']=[1,2,3,4]#add new key value pair in dictionary
print(stu)
stu['science']=[2,6,8,9]#we can change values also of associated key
print(stu)
ml flow apache spark



{'one': 2, 'two': 4, (12, 13): 5, 'maths': [1, 2, 3, 4]}
2
{'one': 2, 'two': 4, (12, 13): 5, 'maths': [1, 2, 3, 4], 'science': [1, 2, 3, 4]}
{'one': 2, 'two': 4, (12, 13): 5, 'maths': [1, 2, 3, 4], 'science': [2, 6, 8, 9]}


In [2]:
import mysql.connector

# Replace these values with your actual database information
host = "20.204.3.99"  # Database host
user = "YTHOR"  # Database username
password = "Yuvraj9983318185"  # Database password
database = "user1"  # Database name

try:
    # Create a connection to the database
    connection = mysql.connector.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )

    if connection.is_connected():
        print("Connected to the database")

        # Perform database operations here

except mysql.connector.Error as e:
    print("Error connecting to the database:", e)

finally:
    # Close the connection when done
    if 'connection' in locals():
        connection.close()
        print("Connection closed")


Error connecting to the database: 2003 (HY000): Can't connect to MySQL server on '20.204.3.99:3306' (10060)


In [4]:
import numpy as np

In [5]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

In [10]:
a=np.array([[1,2,3,4],[2,3,4,5]])
print(a)#there is no commas in the output this makes it different from list
a.shape

[[1 2 3 4]
 [2 3 4 5]]


(2, 4)

In [11]:
a.ndim#GIVES THE DIMENSION OF THE ARRAY

2

In [13]:
b=np.array([[[4]]])
b.shape
print(b)


[[[4]]]


In [40]:
#create an array of (5,4) and (3,1,2)  and (3,0,2)shape
c=np.array([[1,2,3,4],[3,4,5,6],[5,6,7,8],[5,6,7,8],[4,5,7,8]])
print(c.shape)
arr3 = np.array([
    [[11, 12]],

    
    [[15, 16]],

    [[3,4]]

])
print(arr3.shape)
ar6=np.array([[[2,3]],[[3,5]],[[5,8]]])
print(ar6.shape)



(5, 4)
(3, 1, 2)
(3, 1, 1)


In [ ]:
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import numpy as np

# Replace with your own JSON key file path and spreadsheet URL
json_keyfile = 'path_to_your_json_key_file.json'
spreadsheet_url = 'your_spreadsheet_url_here'

# Authenticate using the JSON key file
scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
credentials = ServiceAccountCredentials.from_json_keyfile_name(json_keyfile, scope)
client = gspread.authorize(credentials)

# Open the specified spreadsheet
spreadsheet = client.open_by_url(spreadsheet_url)
worksheet = spreadsheet.get_worksheet(0)  # You can specify the worksheet index

# Get all values from the worksheet
values = worksheet.get_all_values()

# Convert the values to a NumPy array
numpy_array = np.array(values)

print(numpy_array)


In [73]:
import numpy as np
z=np.zeros((3,4),dtype=np.int8)
print(z)

k=np.ones((2,3),dtype=float)
print(k)

j=np.arange(10,100)
print(j)

t=np.linspace(1,2,num=5,endpoint=False)#whether to include the last value or not 
print(t)
t[0]=67#only value mutable not size mutable
print(t)


pkm=np.array([np.arange(1,5),np.arange(10,14)])
print(pkm)
print(pkm[0])#print first row
print(pkm[0,0])#print first element of first row
print(pkm[0:2,1:3])#array slicing for 2d array
jkt=np.array([np.arange(1,37)])
print(jkt)

h=jkt.reshape(3,4,3)
print(h)
print(h[0::2,1::2,1::2])

ko=np.zeros((4,4,7,2),dtype=np.int8)
print(ko)
kp=[[[[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]]


 [[[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]]


 [[[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]]


 [[[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]]]


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
[1.  1.2 1.4 1.6 1.8]
[67.   1.2  1.4  1.6  1.8]
[[ 1  2  3  4]
 [10 11 12 13]]
[1 2 3 4]
1
[[ 2  3]
 [11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32 33 34 35 36]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[[[ 5]
  [11]]

 [[29]
  [35]]]
[[[[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]]

  [[0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0]
   [0 0

In [2]:
import numpy as np
a=np.array([np.arange(1,6),np.arange(11,16)])
t=[1,2,3]#print 2nd 3rd and 4th element
print(a[0,t])#fancy indexing 

[2 3 4]


In [ ]:
#to use conditions and get a numpy array as result

In [6]:
c=np.array([1,9,6,4,2,7,6,5])
b=c>4
print(b)
k=c[b]#filtering elements greater than 4
print(k)

[False  True  True False False  True  True  True]
[9 6 7 6 5]


In [9]:
c=np.array([1,9,6,4,2,7,6,5])
arr7=c.reshape((2,4))
c[0]=67
print(arr7)
#so conclusion is c and arr7 is pointing to same array if we change any one the change in other also can be seen so both point  to soame location
#slicing and reshaping points to the same memory location and make chagnes in same array it creates view to save memory and time to make fast operations  
arr7=c.reshape((2,4)).copy()# this will allocate different memory location

[[67  9  6  4]
 [ 2  7  6  5]]


In [25]:
ar8=np.array([[67,9  ,6  ,4],
 [ 2 , 7  ,6  ,5]])
total=np.sum(ar8)#sums all the values of array
print(total)
#axis=0 then vertical 
#axis=1 then horizontal
print(np.sum(ar8,axis=0))
print(np.mean(ar8,dtype=int))
print(np.mean(ar8,dtype=int,axis=1))

pi=round(3.123,ndigits=1)#using round function
print(pi)


arrt8=np.array([[67,9  ,6  ,4],
 [ 2 , 7  ,6  ,5]])
print(np.mean(arrt8,where=[[True],[False]]))#only first block mean will be taken

106
[69 16 12  9]
13
[21  5]
3.1
21.5
